export enum Environment {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
  TEST = 'test',
}

export const isProduction = (): boolean =>
  process.env.NODE_ENV === Environment.PRODUCTION;

export const isDevelopment = (): boolean =>
  process.env.NODE_ENV === Environment.DEVELOPMENT;

export const isTest = (): boolean => process.env.NODE_ENV === Environment.TEST;

export enum Config {
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DB = 'POSTGRES_DB',
  DB_PORT = 'DB_PORT',
  DATABASE_URL = 'DATABASE_URL',
  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  ACCESS_TOKEN_TTL = 'ACCESS_TOKEN_TTL',
  REFRESH_TOKEN_TTL = 'REFRESH_TOKEN_TTL',
  REFRESH_COOKIE_NAME = 'REFRESH_COOKIE_NAME',
  COOKIE_SECURE = 'COOKIE_SECURE',
  COOKIE_SAMESITE = 'COOKIE_SAMESITE',
  COOKIE_DOMAIN = 'COOKIE_DOMAIN',
  PASSWORD_ALGO = 'PASSWORD_ALGO',
  TOKEN_HASH_PEPPER = 'TOKEN_HASH_PEPPER',
  APP_FRONTEND_URL = 'APP_FRONTEND_URL',
  MAIL_HOST = 'MAIL_HOST',
  MAIL_PORT = 'MAIL_PORT',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',
  MAIL_FROM = 'MAIL_FROM',
  APP_NAME = 'APP_NAME',
  APP_PORT = 'APP_PORT',
  THROTTLE_TTL = 'THROTTLE_TTL',
  THROTTLE_LIMIT = 'THROTTLE_LIMIT',
  ENVIRONMENT = 'ENVIRONMENT',
}
